import "./globals.css";
import localFont from 'next/font/local';

const montserrat = localFont({
  src: '/fonts/Montserrat-Regular.woff2', // ✅ Correct path (public/fonts)
  weight: '400',
  style: 'normal',
});

export const metadata = {
  title: "Farhan Zafar | Web Developer & AI Specialist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
